#!/bin/sh

nixfmt=$(git config --type=bool hooks.nixfmt)

if [ "$nixfmt" != true ]; then
	exit 0
fi

# Redirect output to stderr.
exec 1>&2

files=$(git diff --cached --name-only --diff-filter=d | grep '\.nix$')

if [ -z "$files" ]; then
	exit 0
fi

echo "$files" | xargs nix fmt
echo "$files" | xargs git add

# Abort on empty commit.
if [ -z "$(git diff --cached --name-only)" ]; then
	# Print error message for empty commit.
	git commit
	exit 1
fi
