image: nixos/unstable
secrets:
- 7f4676f8-c40c-498b-a4d4-a644037f559c
sources:
- git@git.sr.ht/~patwid/nixos
tasks:
- check: |
    cd nixos
    nix \
      --extra-experimental-features nix-command \
      --extra-experimental-features flakes \
      flake check
