#!/bin/sh

# Redirect output to stderr.
#exec 1>&2

# for file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$'); do
# 	nix fmt "$file"
# 	# git add "$file"
# done

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$')
if [ -n "$files" ]; then
	nix fmt $files
	# git add $files
fi

git_dir="$(git rev-parse --git-dir)"
if [ -x "$git_dir/hooks/pre-commit" ]; then
	exec "$git_dir/hooks/pre-commit"
fi
